api_version = "2025-10"
[[extensions]]
# Change the merchant-facing name of the extension in locales/en.default.json
name = "t:name"
handle = "pudo-block"
type = "ui_extension"
uid = "b3dd8e92-058d-b851-8462-2f5ee70f13b4ebba80a5"

# Only 1 target can be specified for each Admin block extension
[[extensions.targeting]]
module = "./src/BlockExtension.jsx"
target = "admin.order-details.block.render"


# Valid extension targets:

# Abandoned checkout detail page
# - admin.abandoned-checkout-details.block.render

# Collection detail pages
# - admin.collection-details.block.render

# Catalog detail page
# - admin.catalog-details.block.render

# Company detail page
# - admin.company-details.block.render
# - admin.company-location.block.render

# Customer detail page
# - admin.customer-details.block.render

# Draft order detail pages
# - admin.draft-order-details.block.render

# Gift card detail page
# - admin.gift-card-details.block.render

# Order detail page
# - admin.order-details.block.render

# Product detail pages
# - admin.product-details.block.render

# Product variant detail pages
# - admin.product-variant-details.block.render
